branch-defaults:
  admin:
    environment: null
    group_suffix: null
global:
  application_name: jws
  branch: admin
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: jws.com
  sc: git
  workspace_type: Application
